[package]
name = "cocos"
version = "0.1.0"
edition = "2024"

[dependencies]
libcocos = { path = "../libcocos", features = ["rayon", "simd"] }
rayon = "1.11.0"
rand = "0.9.2"
anyhow = "1.0.99"
clap = { version = "4.5", features = ["derive"] }
rand_chacha = "0.9.0"
num_cpus = "1.17.0"