[package]
name = "libcocos"
version = "0.1.0"
edition = "2024"
description = "Parallel implementation of the Approximately Unbiased test for independent likelihoods."
repository = "https://github.com/Cydhra/cocos/"
license = "MIT OR Apache-2.0"
keywords = ["bio", "bioinformatics", "phylogenetics", "statistics", "bootstrap"]
categories = ["science", "science::bioinformatics", "mathematics"]

[dependencies]
# bootstrapping
rand = "0.9.2"

# statistics
statrs = "0.18.0"

# parallelization
rayon = { version = "1.11.0", optional = true }

# serialization
serde = { version = "1.0.221", optional = true, features = ["derive"] }

[features]
simd = []