[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
libcocos = { path = "../libcocos", features = ["rayon"] }
cocos-parse = { path = "../cocos-parse" }

anyhow = "1.0.99"

rand = "0.9.2"
rand_chacha = "0.9.0"

[[bench]]
name = "stability"
harness = false